#!/usr/bin/env python3
"""Scaffold a Remotion video project.

Creates a project directory with src/Root.tsx, compositions, and
brand configuration.

Usage:
    python scripts/remotion_scaffold.py my-video
    python scripts/remotion_scaffold.py my-video --brand-dir ./brand --title "Product Demo"
"""

import argparse
import json
import re
import sys
from pathlib import Path


def read_brand_visual(brand_dir: str) -> dict:
    """Read brand/VISUAL.md and extract colors and typography."""
    visual_path = Path(brand_dir) / "VISUAL.md"
    brand = {
        "primary": "#1a1a2e",
        "secondary": "#16213e",
        "accent": "#0f3460",
        "text": "#e4e4e4",
        "background": "#0a0a0a",
        "font_display": "Space Grotesk",
        "font_body": "Inter",
        "font_mono": "JetBrains Mono",
    }

    if not visual_path.exists():
        return brand

    text = visual_path.read_text(encoding="utf-8")

    color_mappings = {
        "primary": r"(?i)primary[^\n]*?(#[0-9a-fA-F]{6})",
        "secondary": r"(?i)secondary[^\n]*?(#[0-9a-fA-F]{6})",
        "accent": r"(?i)accent[^\n]*?(#[0-9a-fA-F]{6})",
        "text": r"(?i)(?:text|foreground)[^\n]*?(#[0-9a-fA-F]{6})",
        "background": r"(?i)background[^\n]*?(#[0-9a-fA-F]{6})",
    }

    for key, pattern in color_mappings.items():
        match = re.search(pattern, text)
        if match:
            brand[key] = match.group(1)

    font_match = re.search(r"(?i)(?:display|heading)\s*(?:font|typeface)[^\n]*?:\s*([A-Z][A-Za-z\s]+)", text)
    if font_match:
        brand["font_display"] = font_match.group(1).strip()

    font_match = re.search(r"(?i)body\s*(?:font|typeface)[^\n]*?:\s*([A-Z][A-Za-z\s]+)", text)
    if font_match:
        brand["font_body"] = font_match.group(1).strip()

    return brand


def generate_package_json(project_name: str) -> str:
    """Generate package.json for Remotion project."""
    pkg = {
        "name": project_name,
        "version": "1.0.0",
        "private": True,
        "scripts": {
            "start": "npx remotion studio",
            "build": "npx remotion render src/index.ts MainComposition out/video.mp4",
            "upgrade": "npx remotion upgrade",
        },
        "dependencies": {
            "@remotion/cli": "^4.0.0",
            "react": "^18.3.0",
            "react-dom": "^18.3.0",
            "remotion": "^4.0.0",
        },
        "devDependencies": {
            "@remotion/eslint-config": "^4.0.0",
            "@types/react": "^18.3.0",
            "typescript": "^5.5.0",
        },
    }
    return json.dumps(pkg, indent=2) + "\n"


def generate_tsconfig() -> str:
    """Generate tsconfig.json."""
    config = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "commonjs",
            "jsx": "react-jsx",
            "strict": True,
            "esModuleInterop": True,
            "skipLibCheck": True,
            "forceConsistentCasingInFileNames": True,
            "outDir": "./dist",
            "rootDir": "./src",
        },
        "include": ["src/**/*"],
    }
    return json.dumps(config, indent=2) + "\n"


def generate_brand_config(brand: dict) -> str:
    """Generate brand configuration TypeScript file."""
    return f"""// Brand configuration
// Generated by content-skills scaffold
// Edit these values or regenerate from brand/VISUAL.md

export const brandColors = {{
  primary: '{brand['primary']}',
  secondary: '{brand['secondary']}',
  accent: '{brand['accent']}',
  text: '{brand['text']}',
  background: '{brand['background']}',
}} as const;

export const brandFonts = {{
  display: '{brand['font_display']}',
  body: '{brand['font_body']}',
  mono: '{brand['font_mono']}',
}} as const;

export const videoDefaults = {{
  fps: 30,
  width: 1920,
  height: 1080,
  durationInFrames: 300, // 10 seconds at 30fps
}} as const;

export type BrandColors = typeof brandColors;
export type BrandFonts = typeof brandFonts;
"""


def generate_root_tsx(title: str, brand: dict) -> str:
    """Generate the Root.tsx composition file."""
    return f"""import {{ Composition }} from 'remotion';
import {{ MainComposition }} from './compositions/MainComposition';
import {{ IntroScene }} from './compositions/IntroScene';
import {{ OutroScene }} from './compositions/OutroScene';
import {{ videoDefaults }} from './brand';

export const RemotionRoot: React.FC = () => {{
  return (
    <>
      <Composition
        id="MainComposition"
        component={{MainComposition}}
        durationInFrames={{videoDefaults.durationInFrames}}
        fps={{videoDefaults.fps}}
        width={{videoDefaults.width}}
        height={{videoDefaults.height}}
        defaultProps={{{{
          title: '{title}',
        }}}}
      />
      <Composition
        id="IntroScene"
        component={{IntroScene}}
        durationInFrames={{90}}
        fps={{videoDefaults.fps}}
        width={{videoDefaults.width}}
        height={{videoDefaults.height}}
        defaultProps={{{{
          title: '{title}',
        }}}}
      />
      <Composition
        id="OutroScene"
        component={{OutroScene}}
        durationInFrames={{90}}
        fps={{videoDefaults.fps}}
        width={{videoDefaults.width}}
        height={{videoDefaults.height}}
      />
    </>
  );
}};
"""


def generate_main_composition(title: str) -> str:
    """Generate the MainComposition component."""
    return f"""import {{ AbsoluteFill, Sequence }} from 'remotion';
import {{ IntroScene }} from './IntroScene';
import {{ OutroScene }} from './OutroScene';
import {{ brandColors }} from '../brand';

interface MainCompositionProps {{
  title: string;
}}

export const MainComposition: React.FC<MainCompositionProps> = ({{ title }}) => {{
  return (
    <AbsoluteFill style={{{{ backgroundColor: brandColors.background }}}}>
      {{/* Intro: frames 0-89 */}}
      <Sequence from={{0}} durationInFrames={{90}}>
        <IntroScene title={{title}} />
      </Sequence>

      {{/* Main content: frames 90-209 */}}
      <Sequence from={{90}} durationInFrames={{120}}>
        <AbsoluteFill
          style={{{{
            justifyContent: 'center',
            alignItems: 'center',
            padding: 80,
          }}}}
        >
          <h2
            style={{{{
              color: brandColors.text,
              fontSize: 48,
              fontFamily: 'Inter, sans-serif',
              textAlign: 'center',
              lineHeight: 1.4,
            }}}}
          >
            Replace this with your main content.
          </h2>
        </AbsoluteFill>
      </Sequence>

      {{/* Outro: frames 210-299 */}}
      <Sequence from={{210}} durationInFrames={{90}}>
        <OutroScene />
      </Sequence>
    </AbsoluteFill>
  );
}};
"""


def generate_intro_scene() -> str:
    """Generate the IntroScene component."""
    return """import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { brandColors, brandFonts } from '../brand';

interface IntroSceneProps {
  title: string;
}

export const IntroScene: React.FC<IntroSceneProps> = ({ title }) => {
  const frame = useCurrentFrame();

  const titleOpacity = interpolate(frame, [0, 30], [0, 1], {
    extrapolateRight: 'clamp',
  });

  const titleY = interpolate(frame, [0, 30], [20, 0], {
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill
      style={{
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: brandColors.background,
      }}
    >
      <h1
        style={{
          color: brandColors.primary,
          fontSize: 72,
          fontFamily: `${brandFonts.display}, sans-serif`,
          fontWeight: 700,
          opacity: titleOpacity,
          transform: `translateY(${titleY}px)`,
          textAlign: 'center',
          maxWidth: '80%',
        }}
      >
        {title}
      </h1>
    </AbsoluteFill>
  );
};
"""


def generate_outro_scene() -> str:
    """Generate the OutroScene component."""
    return """import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { brandColors, brandFonts } from '../brand';

export const OutroScene: React.FC = () => {
  const frame = useCurrentFrame();

  const opacity = interpolate(frame, [0, 30], [0, 1], {
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill
      style={{
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: brandColors.background,
      }}
    >
      <div style={{ opacity, textAlign: 'center' }}>
        <h2
          style={{
            color: brandColors.primary,
            fontSize: 56,
            fontFamily: `${brandFonts.display}, sans-serif`,
            fontWeight: 700,
            marginBottom: 16,
          }}
        >
          Thank You
        </h2>
        <p
          style={{
            color: brandColors.text,
            fontSize: 28,
            fontFamily: `${brandFonts.body}, sans-serif`,
            opacity: 0.7,
          }}
        >
          example.com
        </p>
      </div>
    </AbsoluteFill>
  );
};
"""


def generate_index_ts() -> str:
    """Generate the entry point index.ts."""
    return """import { registerRoot } from 'remotion';
import { RemotionRoot } from './Root';

registerRoot(RemotionRoot);
"""


def scaffold(project_name: str, brand_dir: str = "brand", title: str | None = None):
    """Create the Remotion project directory structure."""
    project_path = Path(project_name)

    if project_path.exists():
        return {"error": f"Directory already exists: {project_name}"}

    display_title = title or project_name.replace("-", " ").replace("_", " ").title()
    brand = read_brand_visual(brand_dir)

    # Create directories
    project_path.mkdir(parents=True)
    (project_path / "src").mkdir()
    (project_path / "src" / "compositions").mkdir()
    (project_path / "out").mkdir()

    # Write files
    (project_path / "package.json").write_text(generate_package_json(project_name))
    (project_path / "tsconfig.json").write_text(generate_tsconfig())
    (project_path / "src" / "index.ts").write_text(generate_index_ts())
    (project_path / "src" / "brand.ts").write_text(generate_brand_config(brand))
    (project_path / "src" / "Root.tsx").write_text(generate_root_tsx(display_title, brand))
    (project_path / "src" / "compositions" / "MainComposition.tsx").write_text(
        generate_main_composition(display_title)
    )
    (project_path / "src" / "compositions" / "IntroScene.tsx").write_text(
        generate_intro_scene()
    )
    (project_path / "src" / "compositions" / "OutroScene.tsx").write_text(
        generate_outro_scene()
    )

    # Create .gitignore
    (project_path / ".gitignore").write_text("node_modules/\nout/\ndist/\n")

    files_created = [
        str(project_path / "package.json"),
        str(project_path / "tsconfig.json"),
        str(project_path / "src" / "index.ts"),
        str(project_path / "src" / "brand.ts"),
        str(project_path / "src" / "Root.tsx"),
        str(project_path / "src" / "compositions" / "MainComposition.tsx"),
        str(project_path / "src" / "compositions" / "IntroScene.tsx"),
        str(project_path / "src" / "compositions" / "OutroScene.tsx"),
        str(project_path / ".gitignore"),
    ]

    return {
        "project": project_name,
        "title": display_title,
        "path": str(project_path.resolve()),
        "files_created": files_created,
        "brand_source": str(Path(brand_dir) / "VISUAL.md") if (Path(brand_dir) / "VISUAL.md").exists() else "defaults",
        "next_steps": [
            f"cd {project_name}",
            "npm install",
            "npx remotion studio",
        ],
    }


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a Remotion video project."
    )
    parser.add_argument("project_name", help="Name of the project directory to create")
    parser.add_argument(
        "--brand-dir",
        "-b",
        default="brand",
        help="Path to brand directory (default: brand/)",
    )
    parser.add_argument(
        "--title",
        "-t",
        default=None,
        help="Video title (default: derived from project name)",
    )

    args = parser.parse_args()
    result = scaffold(args.project_name, args.brand_dir, args.title)

    if "error" in result:
        print(json.dumps(result, indent=2))
        sys.exit(1)

    print(json.dumps(result, indent=2))
    print(f"\nProject scaffolded at: {result['path']}", file=sys.stderr)
    print("Next steps:", file=sys.stderr)
    for step in result["next_steps"]:
        print(f"  {step}", file=sys.stderr)


if __name__ == "__main__":
    main()
