#!/usr/bin/env python3
"""Scaffold a Slidev presentation project.

Creates a directory with slides.md, package.json, and brand CSS
derived from brand/VISUAL.md if available.

Usage:
    python scripts/slidev_scaffold.py my-presentation
    python scripts/slidev_scaffold.py my-deck --brand-dir ./brand --title "Q4 Strategy"
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path


def read_brand_visual(brand_dir: str) -> dict:
    """Read brand/VISUAL.md and extract colors and typography."""
    visual_path = Path(brand_dir) / "VISUAL.md"
    brand = {
        "primary": "#1a1a2e",
        "secondary": "#16213e",
        "accent": "#0f3460",
        "text": "#e4e4e4",
        "background": "#0a0a0a",
        "font_display": "Space Grotesk",
        "font_body": "Inter",
        "font_mono": "JetBrains Mono",
    }

    if not visual_path.exists():
        return brand

    text = visual_path.read_text(encoding="utf-8")

    # Try to extract hex colors by label
    color_mappings = {
        "primary": r"(?i)primary[^\n]*?(#[0-9a-fA-F]{6})",
        "secondary": r"(?i)secondary[^\n]*?(#[0-9a-fA-F]{6})",
        "accent": r"(?i)accent[^\n]*?(#[0-9a-fA-F]{6})",
        "text": r"(?i)(?:text|foreground)[^\n]*?(#[0-9a-fA-F]{6})",
        "background": r"(?i)background[^\n]*?(#[0-9a-fA-F]{6})",
    }

    for key, pattern in color_mappings.items():
        match = re.search(pattern, text)
        if match:
            brand[key] = match.group(1)

    # Try to extract font families
    font_match = re.search(r"(?i)(?:display|heading)\s*(?:font|typeface)[^\n]*?:\s*([A-Z][A-Za-z\s]+)", text)
    if font_match:
        brand["font_display"] = font_match.group(1).strip()

    font_match = re.search(r"(?i)body\s*(?:font|typeface)[^\n]*?:\s*([A-Z][A-Za-z\s]+)", text)
    if font_match:
        brand["font_body"] = font_match.group(1).strip()

    return brand


def generate_package_json(project_name: str) -> str:
    """Generate package.json for Slidev project."""
    pkg = {
        "name": project_name,
        "private": True,
        "scripts": {
            "dev": "slidev",
            "build": "slidev build",
            "export": "slidev export",
        },
        "dependencies": {
            "@slidev/cli": "^0.49.0",
            "@slidev/theme-default": "latest",
        },
    }
    return json.dumps(pkg, indent=2) + "\n"


def generate_slides_md(title: str, brand: dict) -> str:
    """Generate the main slides.md file."""
    return f"""---
theme: default
title: "{title}"
info: |
  ## {title}
  Presentation created with Slidev and content-skills.
class: text-center
drawings:
  persist: false
transition: slide-left
mdc: true
---

# {title}

<div class="pt-12">
  <span class="px-2 py-1 rounded cursor-pointer" hover="bg-white bg-opacity-10">
    Press <kbd>space</kbd> to continue
  </span>
</div>

---
transition: fade-out
---

# Agenda

<v-clicks>

- Point one
- Point two
- Point three
- Point four

</v-clicks>

---

# Section One

Content goes here. Replace this with your actual content.

- Key point with supporting detail
- Another point backed by evidence
- A third point that advances the argument

---

# Section Two

More content here.

```python
# Code examples render with syntax highlighting
def example():
    return "Slidev supports code blocks natively"
```

---
layout: center
class: text-center
---

# Key Takeaway

The single most important thing the audience should remember.

---
layout: end
---

# Thank You

[Learn more](https://example.com)
"""


def generate_brand_css(brand: dict) -> str:
    """Generate brand-aligned CSS for the Slidev theme."""
    return f"""/* Brand-aligned Slidev styles
 * Generated by content-skills scaffold
 * Customize these values or replace with brand/VISUAL.md overrides
 */

:root {{
  /* Brand colors */
  --slidev-theme-primary: {brand['primary']};
  --slidev-theme-secondary: {brand['secondary']};
  --slidev-theme-accent: {brand['accent']};

  /* Typography */
  --slidev-font-display: '{brand['font_display']}', ui-sans-serif, system-ui, sans-serif;
  --slidev-font-body: '{brand['font_body']}', ui-sans-serif, system-ui, sans-serif;
  --slidev-font-mono: '{brand['font_mono']}', ui-monospace, monospace;
}}

/* Slide defaults */
.slidev-layout {{
  background: {brand['background']};
  color: {brand['text']};
  font-family: var(--slidev-font-body);
}}

/* Headings */
.slidev-layout h1,
.slidev-layout h2,
.slidev-layout h3 {{
  font-family: var(--slidev-font-display);
  color: {brand['primary']};
}}

.slidev-layout h1 {{
  font-size: 2.5rem;
  font-weight: 700;
  line-height: 1.2;
}}

.slidev-layout h2 {{
  font-size: 1.875rem;
  font-weight: 600;
}}

/* Code blocks */
.slidev-layout pre,
.slidev-layout code {{
  font-family: var(--slidev-font-mono);
}}

/* Links */
.slidev-layout a {{
  color: {brand['accent']};
  text-decoration: none;
  border-bottom: 1px solid transparent;
  transition: border-color 0.2s;
}}

.slidev-layout a:hover {{
  border-bottom-color: {brand['accent']};
}}

/* Accent elements */
.slidev-layout kbd {{
  background: {brand['secondary']};
  border-radius: 4px;
  padding: 2px 6px;
  font-size: 0.875em;
  font-family: var(--slidev-font-mono);
}}
"""


def scaffold(project_name: str, brand_dir: str = "brand", title: str | None = None):
    """Create the Slidev project directory structure."""
    project_path = Path(project_name)

    if project_path.exists():
        return {"error": f"Directory already exists: {project_name}"}

    display_title = title or project_name.replace("-", " ").replace("_", " ").title()
    brand = read_brand_visual(brand_dir)

    # Create directories
    project_path.mkdir(parents=True)
    (project_path / "styles").mkdir()

    # Write files
    (project_path / "package.json").write_text(generate_package_json(project_name))
    (project_path / "slides.md").write_text(generate_slides_md(display_title, brand))
    (project_path / "styles" / "brand.css").write_text(generate_brand_css(brand))

    # Create .gitignore
    (project_path / ".gitignore").write_text("node_modules/\ndist/\n.slidev/\n")

    files_created = [
        str(project_path / "package.json"),
        str(project_path / "slides.md"),
        str(project_path / "styles" / "brand.css"),
        str(project_path / ".gitignore"),
    ]

    return {
        "project": project_name,
        "title": display_title,
        "path": str(project_path.resolve()),
        "files_created": files_created,
        "brand_source": str(Path(brand_dir) / "VISUAL.md") if (Path(brand_dir) / "VISUAL.md").exists() else "defaults",
        "next_steps": [
            f"cd {project_name}",
            "npm install",
            "npm run dev",
        ],
    }


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a Slidev presentation project."
    )
    parser.add_argument("project_name", help="Name of the project directory to create")
    parser.add_argument(
        "--brand-dir",
        "-b",
        default="brand",
        help="Path to brand directory (default: brand/)",
    )
    parser.add_argument(
        "--title",
        "-t",
        default=None,
        help="Presentation title (default: derived from project name)",
    )

    args = parser.parse_args()
    result = scaffold(args.project_name, args.brand_dir, args.title)

    if "error" in result:
        print(json.dumps(result, indent=2))
        sys.exit(1)

    print(json.dumps(result, indent=2))
    print(f"\nProject scaffolded at: {result['path']}", file=sys.stderr)
    print("Next steps:", file=sys.stderr)
    for step in result["next_steps"]:
        print(f"  {step}", file=sys.stderr)


if __name__ == "__main__":
    main()
